import { addDays, differenceInCalendarDays, format, parseISO, startOfDay } from "date-fns";
import type { FollowUp, Protocol, ProtocolStep, Treatment, Visit } from "./types";

/** How many follow-ups one step produces. A step with no `repeat` produces one. */
export function stepOccurrences(step: ProtocolStep): number {
  return Math.max(1, step.repeat?.times ?? 1);
}

/** Days between occurrences of a recurring step; 0 for a one-off step. */
export function stepInterval(step: ProtocolStep): number {
  return step.repeat?.everyDays ?? 0;
}

/** Day offset from the visit for the nth occurrence (n is 1-based). */
export function occurrenceOffset(step: ProtocolStep, occurrence: number): number {
  return step.offsetDays + (occurrence - 1) * stepInterval(step);
}

/** A logged visit spawns follow-ups from every protocol step attached to its
 *  treatments — the whole series at once for a recurring step, so a monthly
 *  course is on the books the moment the first session is logged and nobody
 *  has to remember to create the next one.
 *
 *  This is the heart of the product: the clinic never has to remember a recall. */
export function followUpsForVisit(
  visit: Visit,
  protocols: Protocol[],
  treatments: Treatment[],
  idPrefix = "fu",
): FollowUp[] {
  const visitDate = startOfDay(parseISO(visit.date));
  const protocolIds = new Set<string>();

  for (const treatmentId of visit.treatmentIds) {
    const treatment = treatments.find((t) => t.id === treatmentId);
    if (treatment?.protocolId) protocolIds.add(treatment.protocolId);
  }

  const created: FollowUp[] = [];
  for (const protocolId of protocolIds) {
    const protocol = protocols.find((p) => p.id === protocolId);
    if (!protocol) continue;
    for (const step of protocol.steps) {
      const seriesLength = stepOccurrences(step);
      for (let occurrence = 1; occurrence <= seriesLength; occurrence++) {
        created.push({
          id:
            seriesLength === 1
              ? `${idPrefix}-${visit.id}-${step.id}`
              : `${idPrefix}-${visit.id}-${step.id}-${occurrence}`,
          patientId: visit.patientId,
          visitId: visit.id,
          protocolId: protocol.id,
          stepId: step.id,
          dueDate: format(addDays(visitDate, occurrenceOffset(step, occurrence)), "yyyy-MM-dd"),
          status: "due",
          occurrence,
          seriesLength,
        });
      }
    }
  }
  return created;
}

export const OPEN_STATUSES: FollowUp["status"][] = ["due", "sent", "confirmed", "snoozed"];

export function isOpen(followUp: FollowUp): boolean {
  return OPEN_STATUSES.includes(followUp.status);
}

/** Effective due date: a snoozed follow-up is not due until the snooze runs out. */
export function effectiveDueDate(followUp: FollowUp): string {
  return followUp.snoozeUntil && followUp.snoozeUntil > followUp.dueDate
    ? followUp.snoozeUntil
    : followUp.dueDate;
}

export function daysUntilDue(followUp: FollowUp, now: Date): number {
  return differenceInCalendarDays(parseISO(effectiveDueDate(followUp)), startOfDay(now));
}

export function isDue(followUp: FollowUp, now: Date): boolean {
  return isOpen(followUp) && daysUntilDue(followUp, now) <= 0;
}

export function isOverdue(followUp: FollowUp, now: Date): boolean {
  return isOpen(followUp) && daysUntilDue(followUp, now) < 0;
}

/** Reactivation value decays with time, so the work list is ranked by urgency,
 *  not simply sorted oldest first. */
export function followUpPriority(followUp: FollowUp, now: Date): number {
  const days = daysUntilDue(followUp, now);
  const statusWeight =
    followUp.status === "confirmed" ? -1000 : followUp.status === "due" ? -100 : 0;
  return statusWeight + days;
}

// ---------------------------------------------------------------------------
// Series
//
// Every follow-up generated by one step of one visit belongs to one series. A
// six-session course is six rows in the data but one thing in the clinic's
// head, so the work list shows the occurrence to act on now and says how far
// through the course the patient is. Without this, one patient on a monthly
// plan buries five other patients' recalls.
// ---------------------------------------------------------------------------

export function seriesKey(followUp: Pick<FollowUp, "visitId" | "stepId">): string {
  return `${followUp.visitId}:${followUp.stepId}`;
}

export interface FollowUpSeries {
  key: string;
  /** the occurrence to act on now: the earliest still-open one */
  head: FollowUp;
  /** open occurrences queued behind the head */
  later: FollowUp[];
  /** how many occurrences of this series are finished */
  completed: number;
  /** occurrences in the whole series */
  length: number;
}

const FINISHED: FollowUp["status"][] = ["done", "booked"];

/**
 * Collapses follow-ups into one row per series, keyed by visit and step.
 * Series with nothing open left are dropped — they belong in the history, not
 * in a work list.
 */
export function openSeries(followUps: FollowUp[]): FollowUpSeries[] {
  const groups = new Map<string, FollowUp[]>();
  for (const followUp of followUps) {
    const key = seriesKey(followUp);
    const group = groups.get(key);
    if (group) group.push(followUp);
    else groups.set(key, [followUp]);
  }

  const series: FollowUpSeries[] = [];
  for (const [key, group] of groups) {
    const sorted = [...group].sort((a, b) => a.occurrence - b.occurrence);
    const open = sorted.filter(isOpen);
    const head = open[0];
    if (!head) continue;
    series.push({
      key,
      head,
      later: open.slice(1),
      completed: sorted.filter((f) => FINISHED.includes(f.status)).length,
      length: head.seriesLength || sorted.length,
    });
  }
  return series;
}
